Fix AttributeError: Replace deprecated tf.log with tf.math.log
TensorFlow 2.x deprecated tf.log in favor of tf.math.log. This was
causing AttributeError when building the model.

Changes:
- model/dec_continuous.py line 178: tf.log -> tf.math.log (2 occurrences)
- util/helper.py line 215: tf.log -> tf.math.log (2 occurrences)
- util/losses.py line 268: tf.log -> tf.math.log (1 occurrence)

Fixes error:
  AttributeError: module 'tensorflow' has no attribute 'log'

This is a TensorFlow 2.x compatibility fix for deprecated API.