Fix AttributeError: Replace deprecated tf.is_finite with tf.math.is_finite
TensorFlow 2.x removed the tf.is_finite function in favor of
tf.math.is_finite. This was causing AttributeError when training
the model.

Changes:
- util/losses.py line 97: tf.is_finite -> tf.math.is_finite (mmd_loss)
- util/losses.py line 132: tf.is_finite -> tf.math.is_finite (correlation_loss)
- util/losses.py line 182: tf.is_finite -> tf.math.is_finite (dann_loss)
- util/losses.py line 222: tf.is_finite -> tf.math.is_finite (difference_loss)

Fixes error:
  AttributeError: module 'tensorflow' has no attribute 'is_finite'

This is a TensorFlow 2.x compatibility fix for deprecated API.